#!/bin/bash

echo "======================================="
echo "🔍 Torrent Searcher - Проверка"
echo "======================================="
echo ""
echo "📁 Структура проекта:"
echo ""
ls -lh /home/user1/.openclaw/workspace/torrent-searcher/ | grep -E "^-|frontend|server|dist"
echo ""
echo "✅ Frontend файлы:"
ls -lh /home/user1/.openclaw/workspace/torrent-searcher/frontend/
echo ""
echo "✅ Backend файлы:"
ls -lh /home/user1/.openclaw/workspace/torrent-searcher/dist/server/src/
echo ""
echo "======================================="
echo "🚀 Запуск сервера:"
echo "======================================="
echo ""
echo "cd /home/user1/.openclaw/workspace/torrent-searcher"
echo "npm start"
echo ""
echo "======================================="
echo "API Endpoints:"
echo "======================================="
echo ""
echo "GET /api/search?q=<query>        - Поиск торрентов"
echo "GET /api/health                  - Проверка здоровья"
echo "GET /api/trackers                - Статус трекеров"
echo ""
echo "======================================="
echo "🌐 Открой в браузере:"
echo "======================================="
echo ""
echo "http://localhost:3000"
echo ""
echo "======================================="
